"""Generate the browser config from model.json, or check it without writing."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
config = json.loads((ROOT / "data/model.json").read_text(encoding="utf-8"))
expected = (
    "// Generated by scripts/build_model.py from data/model.json. Do not edit.\n"
    "window.RSVModelData = "
    + json.dumps(config, ensure_ascii=False, indent=2)
    + ";\n"
)
target = ROOT / "js/model-data.js"
if args.check:
    if not target.exists() or target.read_text(encoding="utf-8") != expected:
        raise SystemExit("Browser config is stale. Run python scripts/build_model.py")
    print("Browser config matches model.json")
else:
    target.write_text(expected, encoding="utf-8")
    print("Generated js/model-data.js")
